name: CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*', 'tech-*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'
      - name: Get dependencies
        run: go mod download
      - name: Run tests
        run: go test ./... -v
      - name: Build binaries
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/preekeeper-linux-amd64 .
          GOOS=windows GOARCH=amd64 go build -o dist/preekeeper-windows-amd64.exe .
          GOOS=darwin GOARCH=amd64 go build -o dist/preekeeper-darwin-amd64 .
      - name: Upload release artifacts (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_id: ${{ github.event.release.id }}
          asset_path: dist
          asset_name: dist
          asset_content_type: application/zip
